### ISSUE TITLE
Elahian

### ISSUE THREAD

**Issue by CodeNameMeh** [Danial-Movahed/SkyroomCustomize#1]
salam :D
nickname khodamo nemibinam
+ age mishe nickname ro احمد bezar thx
+ auto update vase extension ham faramoush nashe chon hey download kardan az inja sakhte
Ty <3

**Comment by Danial-Movahed** [comment]
Salaam
Bashe roosh kar mikonam

**Comment by Danial-Movahed** [comment]
Bebin man alan check kardam. Kar mikone. Nemidoonam chera vase to injoorie
Esmeto avaz mikonam va ye chand ta kar dige ham mikonam baad update midam

**Comment by Danial-Movahed** [comment]
Akharin update ro check kon.
Ye bug ro baraye esme to fix kardam.
Va inke auto update ezafe kardam.
