### ISSUE TITLE
Tagging issue

### ISSUE THREAD

**Issue by CodeNameMeh** [Danial-Movahed/SkyroomCustomize#2]
yo dobare chetori joone del
vaqti rooye kesi ke toro tag karde reply mikni payam khodet ham be onvan payam tag shde neshun dade mishe
Ty <3
![image_2022-03-15_105138](https://user-images.githubusercontent.com/101499803/158326612-00663c93-22ed-48cb-979b-153226379a98.png)

**Comment by Danial-Movahed** [comment]
salaam
hmmmmmm.
Ajibe.
Hallesh mikonam, mamnoon az inke etela dadi

**Comment by Danial-Movahed** [comment]
Fixed :))

Baraye update, ye bar browser ro beband baz kon.
